### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by daedrixxx2** [julianxhokaxhiu/FF7SND#1]
I tried opening the exe, and it told me to install .NET 5, which I did, the (x64) ver.
Now when I double click the exe nothing happens.

**Comment by julianxhokaxhiu** [comment]
You should be able to open the app once you install .NET 5 correctly. Not sure what you current issue is.

**Comment by daedrixxx2** [comment]
Is anything else required to open it? Visual Studio 2019, etc.?

**Comment by julianxhokaxhiu** [comment]
> Is anything else required to open it? Should I install the (x86) ver., Visual Studio 2019, etc.?

Should be multi-arch, but consider installing the x86 runtime version too.

**Comment by daedrixxx2** [comment]
Nope. I tried installing the x86 ver. as well and  it doesn't work...

Sorry to stretch it... but if you've extracted the wav files and they work without crashes, could you upload them somewhere, so we that want to use the original sfx can use them? Thanks.

**Comment by julianxhokaxhiu** [comment]
> Nope. I tried installing the x86 ver. as well and it doesn't work...
> 
> Sorry to stretch it... but if you've extracted the wav files and they work without crashes, could you upload them somewhere, so we that want to use the original sfx can use them? Thanks.

Please let's not mix issues. If you're not able to run FF7SND I'm not sure how to help you out. It should just run. Double check your antivirus is not blocking it. Also, not sure on which OS are you but find a way to figure out why it's not running.

Therefore I'll close the issue as it's not related to this project in particular.
